### ISSUE TITLE
How to understand the output scores?

### ISSUE THREAD

**Issue by weedwind** [parlance/ctcdecode#74]
Hi, 

During decoding, I used top-5 best paths. When I look at the output scores returned by the decoder, I found 2 things that I don't understand:

1. The scores are in ascending order, starting from the smallest one. Since it's the "top" N best, why is the first score the smallest?
2. Some scores (the largest ones) are greater than 1. I am wondering since they are log probabilities, should they be less than 0?

So, how should I interpret the scores?

Thank you so much for any help

**Comment by joshemorris** [comment]
Hey @weedwind 

The decoder actually works with log base e probabilities, since a lot of the probabilities are close to 0. This means the probabilities are actually negative. 0.0 being 100% probability and negative infinity being 0% probability. 

In addition to this, Baidu actually modifies the values further at the end of decoding by removing the word insertion bonus/discount and language model scoring:
https://github.com/parlance/ctcdecode/blob/master/ctcdecode/src/ctc_beam_search_decoder.cpp#L178-L181

They also change the sign of this score here:
https://github.com/parlance/ctcdecode/blob/master/ctcdecode/src/decoder_utils.cpp#L61-L62

Personally, I think the decoder should be modified to just return the beam score without the extra processing. The returned beam search is in the correct order according to the beam scores though. Hopefully, this answers your question!

**Comment by ryanleary** [comment]
By Baidu removing the LM portion of the score, they can then use the returned probabilities to easily re-score with a better language model.
